FROM prom/prometheus:v2.51.0
COPY prometheus.yml /etc/prometheus/prometheus.yml
EXPOSE 9090
HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
    CMD nc -z localhost 9090 || exit 1
CMD ["/bin/prometheus", "--config.file=/etc/prometheus/prometheus.yml", "--web.external-url=/metrics", "--web.route-prefix=/"]
