global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prod-e-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['${BACKEND_ALB_HOST}:3000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
