name: Deploy Production Experience
# Automated deployment workflow for the Production Experience project
# For complete documentation, see .github/CICD.md

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7  # Updated to 1.5.7 for better compatibility

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Debug - Check environment
        run: |
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v
          echo "Working directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Content of cdktf.json:"
          cat cdktf.json
          echo "File encoding check:"
          file cdktf.json
          echo "Check for BOM in cdktf.json:"
          hexdump -C cdktf.json | head -1

      - name: Install cdktf-cli
        run: |
          npm install -g cdktf-cli@0.20.7  # Updated to 0.20.7 for better compatibility
          echo "CDKTF version:"
          cdktf --version

      - name: Install packages
        run: npm ci --legacy-peer-deps

      - name: Clean cdktf.out and .gen directories
        run: |
          rm -rf cdktf.out
          rm -rf .gen

      - name: Run tests
        run: npm test

      - name: Fix package version conflicts
        run: |
          npm uninstall cdktf
          npm install cdktf@0.20.7 --save --legacy-peer-deps  # Match CLI version

      - name: Set environment variable to suppress jsii warnings
        run: echo "JSII_SUPPRESS_UPGRADE_PROMPT=1" >> $GITHUB_ENV

      - name: Get dependencies
        run: cdktf get

      - name: Synthesize
        run: npm run synth

      - name: Create Lambda zip file
        run: |
          mkdir -p node_modules/backup
          cp infrastructure/lambda/backup.js node_modules/backup/
          cd node_modules/backup
          zip -r backup.zip .
          cp backup.zip ../../
          cd ../../
          mv backup.zip dummy-backup.zip
          cp dummy-backup.zip cdktf.out/stacks/prod-e/

      - name: Debug - Check state before imports
        run: |
          cd cdktf.out/stacks/prod-e/
          terraform init -upgrade
          terraform state list > state-before-imports.log
          cat state-before-imports.log
          cd ../../

      - name: Clear conflicting state entries
        run: |
          cd cdktf.out/stacks/prod-e/
          terraform init -upgrade
          set +e
          terraform state list | grep -q "aws_db_subnet_group.prode_rds_newsubnetgroup_8B244C0C" && terraform state rm aws_db_subnet_group.prode_rds_newsubnetgroup_8B244C0C
          terraform state list | grep -q "aws_iam_role.prode_ecs_ecstaskexecutionrole_20EAF6F9" && terraform state rm aws_iam_role.prode_ecs_ecstaskexecutionrole_20EAF6F9
          terraform state list | grep -q "aws_iam_role.prode_ecs_ecstaskrole_83A127B2" && terraform state rm aws_iam_role.prode_ecs_ecstaskrole_83A127B2
          terraform state list | grep -q "aws_lb.prode_alb_5B6BC7FD" && terraform state rm aws_lb.prode_alb_5B6BC7FD
          terraform state list | grep -q "aws_lb_target_group.prode_alb_ecstargetgroup_D11F7D5C" && terraform state rm aws_lb_target_group.prode_alb_ecstargetgroup_D11F7D5C
          terraform state list | grep -q "aws_lb_target_group.prode_alb_grafanatargetgroup_F3AF7448" && terraform state rm aws_lb_target_group.prode_alb_grafanatargetgroup_F3AF7448
          terraform state list | grep -q "aws_lb_target_group.prode_alb_prometheustargetgroup_F7AD68CC" && terraform state rm aws_lb_target_group.prode_alb_prometheustargetgroup_F7AD68CC
          terraform state list | grep -q "aws_lambda_function.prode_backup_backuplambda_D9B46980" && terraform state rm aws_lambda_function.prode_backup_backuplambda_D9B46980
          terraform state list | grep -q "aws_s3_bucket.prode_backup_backupbucket_A17FE2F3" && terraform state rm aws_s3_bucket.prode_backup_backupbucket_A17FE2F3
          set -e
          cd ../../

      - name: Initialize Terraform and execute import script
        run: |
          chmod +x import-commands.sh
          ls -l import-commands.sh
          cd cdktf.out/stacks/prod-e/
          ls -l ../../import-commands.sh
          terraform init -upgrade
          echo "Attempting to run import script: $(ls -l /home/runner/work/prod-e/prod-e/import-commands.sh)"
          sh /home/runner/work/prod-e/prod-e/import-commands.sh > import-commands.log 2>&1 || echo "Script failed, check log"
          cat import-commands.log
          cd ../../

      - name: Debug - Check state after imports
        run: |
          cd cdktf.out/stacks/prod-e/
          terraform init -upgrade
          terraform state list > state-after-imports.log
          cat state-after-imports.log
          grep "aws_db_subnet_group.prode_rds_newsubnetgroup_8B244C0C" state-after-imports.log || { echo "Error: DB subnet group not imported"; exit 1; }
          grep "aws_iam_role.prode_ecs_ecstaskexecutionrole_20EAF6F9" state-after-imports.log || { echo "Error: ECS task execution role not imported"; exit 1; }
          grep "aws_iam_role.prode_ecs_ecstaskrole_83A127B2" state-after-imports.log || { echo "Error: ECS task role not imported"; exit 1; }
          grep "aws_lb.prode_alb_5B6BC7FD" state-after-imports.log || { echo "Error: ALB not imported"; exit 1; }
          grep "aws_lb_target_group.prode_alb_ecstargetgroup_D11F7D5C" state-after-imports.log || { echo "Error: ECS target group not imported"; exit 1; }
          grep "aws_lb_target_group.prode_alb_grafanatargetgroup_F3AF7448" state-after-imports.log || { echo "Error: Grafana target group not imported"; exit 1; }
          grep "aws_lb_target_group.prode_alb_prometheustargetgroup_F7AD68CC" state-after-imports.log || { echo "Error: Prometheus target group not imported"; exit 1; }
          grep "aws_lambda_function.prode_backup_backuplambda_D9B46980" state-after-imports.log || { echo "Error: Lambda function not imported"; exit 1; }
          grep "aws_s3_bucket.prode_backup_backupbucket_A17FE2F3" state-after-imports.log || { echo "Error: S3 bucket not imported"; exit 1; }
          cd ../../

      - name: Deploy
        run: cdktf deploy --auto-approve

  resource-check:
    needs: deploy
    uses: ./.github/workflows/resource-check.yml
    secrets: inherit
