name: Deploy Infrastructure
# Automated deployment workflow for the Production Experience project
# For complete documentation, see .github/CICD.md

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: 18.x }
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Debug steps
      - name: Debug - Check JSON Files
        run: |
          echo "Checking JSON files..."
          echo "cdktf.json:"
          cat cdktf.json
          echo ""
          echo "Checking for BOM markers or special characters:"
          hexdump -C cdktf.json | head -5
          echo ""
          echo "Validating cdktf.json:"
          node -e "console.log(JSON.parse(require('fs').readFileSync('cdktf.json', 'utf8')))"

      - run: npm install -g cdktf-cli@0.19.0
      - run: npm ci
      - run: cdktf get
      - run: npm run synth
      - run: chmod +x scripts/monitoring/resource_check.sh
      - run: scripts/monitoring/resource_check.sh
      - run: npm test # Run backend tests
      - run: cdktf deploy --auto-approve

  resource-check:
    needs: deploy
    uses: ./.github/workflows/resource-check.yml
    secrets: inherit
